version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sochigu_db
    environment:
      POSTGRES_DB: sochigu_contest
      POSTGRES_USER: sochigu
      POSTGRES_PASSWORD: sochigu_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sochigu_backend
    env_file: ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sochigu_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  uploads:
